import { Navigation } from './components/shared/navigation/Navigation'
import '../styles/globals.css'
import React from 'react'
import styles from './Layout.module.css'
import { Footer } from './components/shared/footer/Footer'
import { StatusContextProvider } from './StatusContextProvider'
import LoadPage from './components/load/LoadPage'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='es'>
      <head>
        <meta charSet='UTF-8' />
        <meta name='description' content='This web provides an information about my worksheet and all my tecnology knowledge' />
        <title>My personal web</title>
      </head>
      <body suppressHydrationWarning>
        <StatusContextProvider>
          <Navigation />
          <LoadPage />
          <article className={styles.children}>
            {children}
          </article>
          <Footer />
        </StatusContextProvider>
      </body>
    </html>
  )
}
