import { Navigation } from './components/shared/navigation/Navigation'
import '../styles/globals.css'
import React, { useContext } from 'react'
import styles from './Layout.module.css'
import { Footer } from './components/shared/footer/Footer'
import { StatusColorContext, StatusContextProvider } from './StatusContextProvider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  // const context = useContext(StatusColorContext)
  return (
    <html lang='es'>
      <head>
        <meta charSet='UTF-8' />
        <meta name='description' content='This web provides an information about my worksheet and all my tecnology knowledge' />
        <title>My personal web</title>
      </head>
      <body suppressHydrationWarning>
        <StatusContextProvider>
          {/* // TODO add animation fill here */}

          {/* <div className={`${styles.fillColor} ${context.state.show ? styles.fill : styles.unfill}`} /> */}

          <Navigation />
          <article className={styles.children}>
            {children}
          </article>
          <Footer />
        </StatusContextProvider>
      </body>
    </html>
  )
}
